/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreeSelectionModel;

/**
 *
 * @author flopezs
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    private String nombre="";
    private String padre="";
    private String rutaCompleta = "";
    private int path=0;
    public Vista() {
        initComponents();
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getRutaCompleta() {
        return rutaCompleta;
    }

    public int getPath() {
        return path;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botones = new javax.swing.ButtonGroup();
        jScrollPaneContenedor = new javax.swing.JScrollPane();
        jTreeLista = new javax.swing.JTree();
        jTextNombre = new javax.swing.JTextField();
        jLabelBusca = new javax.swing.JLabel();
        jButtonAgregar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jRadioButtonPDF = new javax.swing.JRadioButton();
        jRadioButtonXlS = new javax.swing.JRadioButton();
        jRadioButtonDoc = new javax.swing.JRadioButton();
        jRadioButtonSubc = new javax.swing.JRadioButton();
        jButtoned = new javax.swing.JButton();
        jLabelTam = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTreeLista.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTreeLista.setSelectionRows(new int[] {0});
        jTreeLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTreeListaMouseClicked(evt);
            }
        });
        jScrollPaneContenedor.setViewportView(jTreeLista);

        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });

        jLabelBusca.setText("Root");

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jLabelNombre.setText("Nombre");

        botones.add(jRadioButtonPDF);
        jRadioButtonPDF.setText("PDF");

        botones.add(jRadioButtonXlS);
        jRadioButtonXlS.setText("XLSX");

        botones.add(jRadioButtonDoc);
        jRadioButtonDoc.setSelected(true);
        jRadioButtonDoc.setText("DOCX");

        botones.add(jRadioButtonSubc);
        jRadioButtonSubc.setText("SUBCARPETA");

        jButtoned.setText("TAMANIO");
        jButtoned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonAgregar)
                            .addComponent(jButtonEliminar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtoned)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombre)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelTam, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButtonPDF)
                            .addComponent(jRadioButtonXlS)
                            .addComponent(jRadioButtonDoc)
                            .addComponent(jRadioButtonSubc))
                        .addGap(0, 14, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jRadioButtonPDF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonXlS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonDoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonSubc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBusca)
                            .addComponent(jLabelTam))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAgregar)
                            .addComponent(jButtoned))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:
        
        TreeSelectionModel smd=jTreeLista.getSelectionModel();
        if (smd.getSelectionCount()>0){
            DefaultMutableTreeNode selectedNode= (DefaultMutableTreeNode) jTreeLista.getSelectionPath().getLastPathComponent();
            DefaultMutableTreeNode newNode=new DefaultMutableTreeNode(nombre);
            selectedNode.add(newNode);
            DefaultTreeModel model=(DefaultTreeModel)jTreeLista.getModel();
            model.reload();
        }
        
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jTreeListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTreeListaMouseClicked
        // TODO add your handling code here:
        
        TreeSelectionModel smd=jTreeLista.getSelectionModel();
        if(smd.getSelectionCount()>0){
            DefaultMutableTreeNode selectedNode= (DefaultMutableTreeNode) jTreeLista.getSelectionPath().getLastPathComponent();
       
        jLabelBusca.setText(selectedNode.getUserObject().toString());
        rutaCompleta="";
            TreeNode[] ruta=selectedNode.getPath();
            for (int i = 0; i < ruta.length; i++) {
            if (i > 0) {
                rutaCompleta += "/";
            }
            rutaCompleta += ruta[i].toString(); // O puedes usar otro método para obtener el nombre del nodo
            }

System.out.println("Ruta completa del nodo: " + rutaCompleta);
       path=selectedNode.getPath().length;
        if(selectedNode!=jTreeLista.getModel().getRoot())
        {
            
            padre=selectedNode.getParent().toString();
        }
        
        
        System.out.println(selectedNode.getPath().length);
       
        }
        
      
    }//GEN-LAST:event_jTreeListaMouseClicked

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        DefaultMutableTreeNode selectedNode= (DefaultMutableTreeNode) jTreeLista.getSelectionPath().getLastPathComponent();
        DefaultTreeModel model=(DefaultTreeModel)jTreeLista.getModel();
        if(selectedNode!=jTreeLista.getModel().getRoot())
        {
            model.removeNodeFromParent(selectedNode);
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreActionPerformed

    private void jButtonedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonedActionPerformed
        // TODO add your handling code here:
       // DefaultMutableTreeNode selectedNode= (DefaultMutableTreeNode) jTreeLista.getSelectionPath().getLastPathComponent();
         //   selectedNode.setUserObject(jTextNombre.getText());
           // DefaultTreeModel model=(DefaultTreeModel)jTreeLista.getModel();
            //model.reload();
    }//GEN-LAST:event_jButtonedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup botones;
    public javax.swing.JButton jButtonAgregar;
    public javax.swing.JButton jButtonEliminar;
    public javax.swing.JButton jButtoned;
    public javax.swing.JLabel jLabelBusca;
    public javax.swing.JLabel jLabelNombre;
    public javax.swing.JLabel jLabelTam;
    public javax.swing.JRadioButton jRadioButtonDoc;
    public javax.swing.JRadioButton jRadioButtonPDF;
    public javax.swing.JRadioButton jRadioButtonSubc;
    public javax.swing.JRadioButton jRadioButtonXlS;
    public javax.swing.JScrollPane jScrollPaneContenedor;
    public javax.swing.JTextField jTextNombre;
    private javax.swing.JTree jTreeLista;
    // End of variables declaration//GEN-END:variables
}
